### ISSUE TITLE
Incompatibility betwen pytest-mproc and native pytest collect-only

### ISSUE THREAD

**Issue by mrobertseidowsky-gpsw** [nak/pytest_mproc#1]
**Environnement**: Ubuntu 20.4, 12cores (6 multi-thread)
**Protocol**:
- The `setup.cfg` file contains:
```
[tool:pytest]
# Specify use of all available cores
addopts = --cores auto
```

- Collect tests: `pytest path_to_my_tests/my_test.py --collect-only`

**Observation**:
- I've got well the collected tests but also a huge error block, here an extract:
```
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 827, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
```

```
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 629, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Expected**:
@nak  Is that possible to make compatible the usage of pytest-mproc with the native --collect-only command line of pytest ?

**Comment by nak** [comment]
I believe I understand the issue and will investigate more and hopefully fix by end of week.

**Comment by nak** [comment]
Version 3.2.8 has been pushed to pypi.  Please confirm this fixes the issue and output is as expected.

**Comment by mrobertseidowsky-gpsw** [comment]
> Version 3.2.8 has been pushed to pypi. Please confirm this fixes the issue and output is as expected.

@nak thanks, it works well!
Just one thing: collecting test takes twice time by using pytest-mproc than without it, I think it's because of the part:
```
Running as RoleEnum.MASTER: MY_IP:None
Waiting for server...
Connected
```
I will use this plugin exclusively on my compute, no distribued computing, so do you have an idea why it takes so long for the connection?

**Comment by nak** [comment]
pushed 3.2.9.   This should remove the overhead.  pytest_mproc preps for some distributed work ahead of time to reduce time when actually executing in multiple processes, but didn't need to so that in this use case.  Please LMK if this resolves the slowness issues.

**Comment by mrobertseidowsky-gpsw** [comment]
> pushed 3.2.9. This should remove the overhead. pytest_mproc preps for some distributed work ahead of time to reduce time when actually executing in multiple processes, but didn't need to so that in this use case. Please LMK if this resolves the slowness issues.

@nak it solves it, thanks again for you reactivity!
