### ISSUE TITLE
Deadlock when too much load 

### ISSUE THREAD

**Issue by mrobertseidowsky-gpsw** [nak/pytest_mproc#3]
**Environnement**: Ubuntu 20.4, 12cores (6 multi-thread) (and ArchLinux 16cores (8 multi-thread))
**Reproduction**:
- Create a huge load, for example, simulate that all your logical cores are used at 100% with:
`stress-ng --cpu 12`
- Run you test program with mproc activated with --cores=BigNumber (ex:20) in a loop (stress test)

**Observation**:
- Sometimes, the test program stay stuck at the end of the tests (aroun 1500 tests, take around 200seconds without multi-processing) and it deadlocks i.e never finish so I've to ^C to abort it.
- If I run in the same condition my test program without mproc there is no deadlock.
- So I'm guessing that mproc is waiting for some ressource somewhere.

@nak can you investiguate that point ? I know that it's not the common use case to test with big number of cores but it can reveal a bad behaviour of the plugin. I unfortunately don't have any stracktrace but if you know how to retrieve it, let me know.

**Comment by mrobertseidowsky-gpsw** [comment]
> **Environnement**: Ubuntu 20.4, 12cores (6 multi-thread) (and ArchLinux 16cores (8 multi-thread))
> **Reproduction**:
> 
> * Create a huge load, for example, simulate that all your logical cores are used at 100% with:
>   `stress-ng --cpu 12`
> * Run you test program with mproc activated with --cores=BigNumber (ex:20) in a loop (stress test)
> 
> **Observation**:
> 
> * Sometimes, the test program stay stuck at the end of the tests (aroun 1500 tests, take around 200seconds without multi-processing) and it deadlocks i.e never finish so I've to ^C to abort the process.
> * If I run in the same condition my test program without mproc there is no deadlock.
> * So I'm guessing that mproc is waiting for some ressource somewhere.
> 
> @nak can you investiguate that point ? I know that it's not the common use case to test with big number of cores but it can reveal a bad behaviour of the plugin. I unfortunately don't have any stracktrace but if you know how to retrieve it, let me know.

**Comment by nak** [comment]
I have pushed out 3.2.10 which may resolve for reasonable number of cores.  One problem seems to be with multiprocessing module itself and its ability to handle large # of connections.  I can only reproduce the problem on my machine by going to #-of-support-cores*10 (I have 12 cores and run with --core=120  i.e., --cores=auto*10)   It happens almost always at that level.  On 96 cores, 

Note that up front, each worker has to connect into a multiprocessing manager.  At high numbers of cores, this initial connect call can hang for some workers.  I cannot control this other than to abort the worker thread once the last test has been "handed out" (meaning all tests are complete or already in progress by other workers).  There will be a message stating the worker could not connect in time and has been aborted.  Note: I cannot control this or fix this.  This seems t be an issue with multiprocessing limitation itself.  

Going to too many cores, of course, does not buy much.  Even if you have I/O overhead and therefore low CPU usage across most tests, for example,  you will still run into  a point where each new worker is just adding overhead and taking CPU away from other workers when over-subscribed.  

Either way, do let me know if this resovles it or if it has improved but is intermittent still (but less so).

**Comment by mrobertseidowsky-gpsw** [comment]
Hello @nak 
Unfortunately, our tests are now slower than with the 3.2.9 version with same numbers of cores. Maybe it's an error on our side in our thread management but the rootcause is superhard to find here. Can you confirm me that with 3.2.10 you have the same performance than with 3.2.9 ?
Another thing: in this example of output, one worker takes 0.05s, another 0.03s so how it is possible to have a time resume around 3s at the end ? 

```
 =============================== STATS ================================
User CPU, System CPU utilization, Add'l memory during run
---------------------------------------------------------
Process Worker-0 executed 2 tests in 0.05 seconds; User CPU: 13.76%, Sys CPU: 14.00%, Mem consumed: 0.044M
Process Worker-1 executed 1 tests in 0.03 seconds; User CPU: 24.39%, Sys CPU: 11.17%, Mem consumed: 0.044M
Process Worker-2 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Worker-3 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Worker-4 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Worker-5 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Worker-6 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Worker-7 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Worker-8 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Worker-9 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Worker-10 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Worker-11 executed 0 tests in -1.00 seconds; User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Process Coordinator executed in 3.05 seconds. User CPU: -1.00%, Sys CPU: -1.00%, Mem consumed: 0.044M
Results (3.24s):
       3 passed
```

**Comment by nak** [comment]
I have uploaded 3.2.11.  This cleans things up with less points for interactions.  I still get a periodic deadlock under hight stress testing (many very short tests across 10*num cores on machine).  But much reduced.  
NOTE:  This will wait for all workers to connect up front, so start up time may increase.  I am beginning to realize the weakness of points within the multiprocessing module.  If I do not wait, the system can beginning being dominated by test processing and the connection requests can never get handled until the very end.  I may have to work more closely with you on this issue if timing seems off on this front.  
ALSO NOTE:  multiprocessing Proxy objects seem to deadlock sometimes if there are too many simulatenous requests it seems.  This is a hard problem to resolve at the moment.  I believe this only happens if you have a lot of very short (almost do-nothing) tests so we may be safe there.

**Comment by nak** [comment]
3.2.16 is out now.  This refactors a lot to cleanup some code, but also restores ability to distribute testing across multiple machines.  I think this should work well.  If it does not i will have to begin setting up your system (OS and all).

**Comment by nak** [comment]
ping

**Comment by mrobertseidowsky-gpsw** [comment]
Hello @nak thanks for you work / improvements/ cleaning ! Unfortunately we decided to not integrate your plugin in our testsuite because we've got too much bad behaviours with it, I choose pytest-xdist despite the fact that there is not your very usefull "group" decorator.
